parameters:
  uploads_directory: '%kernel.project_dir%/public/uploads'
  cleverage_processes: '%kernel.project_dir%/config/packages'
  process_logs_dir: '%kernel.logs_dir%/process'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $processLogDir: '%process_logs_dir%'
      $indexLogs: '%clever_age_process_ui.index_logs.enabled%'
      $indexLogsLevel: '%clever_age_process_ui.index_logs.level%'

  CleverAge\ProcessUiBundle\:
    resource: '../src'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Tests/'
      - '../src/Migrations'

  CleverAge\ProcessUiBundle\Monolog\Handler\ProcessLogHandler:
    arguments: ['%process_logs_dir%']