parameters:
  upload_directory: '%kernel.project_dir%/var/storage/uploads'
services:
  _defaults:
    autowire: true
    autoconfigure: true

  CleverAge\ProcessUiBundle\:
    resource: '../src'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Tests/'
      - '../src/Migrations'
